export default {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.mjs'],
  extensionsToTreatAsEsm: ['.ts'],
  moduleNameMapper: {
    '^/smartgrind/(.*)$': '<rootDir>/public/$1',
    '^\\.\\./public/modules/(.*)\\.js$': '<rootDir>/public/modules/$1.ts',
    '^\\./public/modules/(.*)\\.js$': '<rootDir>/public/modules/$1.ts',
    '^\\./api/(.*)\\.js$': '<rootDir>/public/modules/api/$1.ts',
    '^\\./renderers/(.*)\\.js$': '<rootDir>/public/modules/renderers/$1.ts',
    '^\\./ui/(.*)\\.js$': '<rootDir>/public/modules/ui/$1.ts',
    '^\\./types\\.js$': '<rootDir>/public/modules/types.ts',
    '^\\./state\\.js$': '<rootDir>/public/modules/state.ts',
    '^\\./data\\.js$': '<rootDir>/public/modules/data.ts',
    '^\\./utils\\.js$': '<rootDir>/public/modules/utils.ts',
    '^\\./renderers\\.js$': '<rootDir>/public/modules/renderers.ts',
    '^\\./app\\.js$': '<rootDir>/public/modules/app.ts',
    '^\\./api\\.js$': '<rootDir>/public/modules/api.ts',
    '^\\./init\\.js$': '<rootDir>/public/modules/init.ts',
    '^\\.\\./types\\.js$': '<rootDir>/public/modules/types.ts',
    '^\\.\\./state\\.js$': '<rootDir>/public/modules/state.ts',
    '^\\.\\./data\\.js$': '<rootDir>/public/modules/data.ts',
    '^\\.\\./utils\\.js$': '<rootDir>/public/modules/utils.ts',
    '^\\.\\./renderers\\.js$': '<rootDir>/public/modules/renderers.ts',
    '^\\.\\./ui\\.js$': '<rootDir>/public/modules/ui/ui.ts',
    '^\\.\\./app\\.js$': '<rootDir>/public/modules/app.ts',
    '^\\.\\./api\\.js$': '<rootDir>/public/modules/api.ts',
    '^\\.\\./init\\.js$': '<rootDir>/public/modules/init.ts',
    '^\\./ui-pull-to-refresh\\.js$': '<rootDir>/public/modules/ui/ui-pull-to-refresh.ts',
    '^\\./ui-sidebar-resizer\\.js$': '<rootDir>/public/modules/ui/ui-sidebar-resizer.ts',
    '^\\./ui-modals\\.js$': '<rootDir>/public/modules/ui/ui-modals.ts',
    '^\\./ui-auth\\.js$': '<rootDir>/public/modules/ui/ui-auth.ts',
    '^\\./ui-bindings\\.js$': '<rootDir>/public/modules/ui/ui-bindings.ts',
    '^\\./ui-constants\\.js$': '<rootDir>/public/modules/ui/ui-constants.ts',
    '^\\./ui-global\\.js$': '<rootDir>/public/modules/ui/ui-global.ts',
    '^\\./ui-markdown\\.js$': '<rootDir>/public/modules/ui/ui-markdown.ts',
    '^\\./ui-navigation\\.js$': '<rootDir>/public/modules/ui/ui-navigation.ts',
    '^\\./ui-problems\\.js$': '<rootDir>/public/modules/ui/ui-problems.ts',
    '^\\./ui-scroll\\.js$': '<rootDir>/public/modules/ui/ui-scroll.ts',
    '^\\./icons\\.js$': '<rootDir>/public/modules/renderers/icons.ts',
    '^\\./sidebar\\.js$': '<rootDir>/public/modules/renderers/sidebar.ts',
    '^\\./problem-cards\\.js$': '<rootDir>/public/modules/renderers/problem-cards.ts',
    '^\\./html-generators\\.js$': '<rootDir>/public/modules/renderers/html-generators.ts',
    '^\\.\\./ui/ui\\.js$': '<rootDir>/public/modules/ui/ui.ts',
    '^\\./ui\\.js$': '<rootDir>/public/modules/ui/ui.ts',
    '^\\./api-sync\\.js$': '<rootDir>/public/modules/api/api-sync.ts',
    '^\\./api-save\\.js$': '<rootDir>/public/modules/api/api-save.ts',
    '^\\./api-load\\.js$': '<rootDir>/public/modules/api/api-load.ts',
    '^\\./api-delete\\.js$': '<rootDir>/public/modules/api/api-delete.ts',
    '^\\./api-reset\\.js$': '<rootDir>/public/modules/api/api-reset.ts',
  },
  transform: {
    '^.+\\.ts$': ['ts-jest', { useESM: true }],
    '^.+\\.(js|mjs)$': ['babel-jest'],
  },
  transformIgnorePatterns: [
    'node_modules/(?!(jest-environment-jsdom|jose)/)',
    'public/modules/.*\\.js$',
  ],
  testMatch: [
    '<rootDir>/tests/**/*.test.(js|ts)',
  ],
  collectCoverageFrom: [
    'public/modules/**/*.(js|ts)',
    'functions/**/*.(js|ts)',
  ],
  moduleFileExtensions: ['js', 'ts', 'mjs'],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  transformIgnorePatterns: [
    'node_modules/(?!(jest-environment-jsdom|jose)/)',
  ],
};
